### PR TITLE
do not open a debugger if libgit2 is not present

### PR DESCRIPTION
**Pull request by estebanlm**
... at least, not immediately :)
instead, react in a nicer way. For now I made this: 

image

### CODE REVIEW

**Comment by estebanlm** [comment]
@tesonep ping ;)

**Comment by Ducasse** [comment]
Esteban you have tests failing.

```
###########
# Summary #
###########

IceTipWorkingCopyBrowserOnUpdatedRepoTest
 ✗ #testItemsHasContextMenu (240ms)
 ✗ #testPackageHasBrowseRepositoryVersionOption (233ms)
 ✗ #testPackageIsShownInList (236ms)
 ✗ #testStatusBarShowsStatusOfRepository (246ms)

IceTipRepositoriesBrowserTest
 ✗ #testAddRepositoryInModelWithoutRefreshDoesNotRefreshList (283ms)
 ✗ #testAddRepositoryInModelWithoutRefreshDoesNotShowNewRepository (258ms)
 ✗ #testAddRepositoryThenRefreshShowsNewRepository (259ms)
 ✗ #testEditRepositoryBranchThenRefreshDoesRefreshList (254ms)
 ✗ #testEditRepositoryBranchWithoutRefreshDoesNotRefreshList (254ms)
 ✗ #testEditRepositoryNameThenRefreshDoesRefreshList (254ms)
 ✗ #testEditRepositoryNameWithoutRefreshDoesNotRefreshList (255ms)
 ✗ #testEditRepositoryStatusThenRefreshDoesRefreshList (254ms)
 ✗ #testEditRepositoryStatusWithoutRefreshDoesNotRefreshList (252ms)
 ✗ #testHasAddButtonOnTheRight (254ms)
 ✗ #testHasFetchAllButtonOnTheLeft (254ms)
 ✗ #testHasSettingsButtonOnTheRight (246ms)
 ✗ #testInitialListShowsElementsInOriginalOrder (249ms)
 ✗ #testListHasContextMenuHasPackagesOptionEnabled (256ms)
 ✗ #testListHasContextMenuHasRepairRepositoryOptionDisabled (258ms)
 ✗ #testListHasContextMenuOnSelection (249ms)
 ✗ #testListShowsNotLoadedProject (260ms)
 ✗ #testListShowsUpToDateProject (256ms)
 ✗ #testSortingByBranchDoesNotFail (261ms)
 ✗ #testSortingByNameDoesNotFail (258ms)
 ✗ #testSortingByStatusDoesNotFail (258ms)
 ✗ #testSortingDescendingByBranchDoesNotFail (257ms)
 ✗ #testSortingDescendingByNameDoesNotFail (259ms)
 ✗ #testSortingDescendingByStatusDoesNotFail (263ms)
 ✗ #testSortingOriginalByBranchDoesNotFail (262ms)
 ✗ #testSortingOriginalByNameDoesNotFail (266ms)
 ✗ #testSortingOriginalByStatusDoesNotFail (267ms)
 ✗ #testTableHasTheCorrectColumns (250ms)

IceMetacelloProjectSourcePropertiesTonel
 ✗ #testInstallBaselineWhenNoSSHIsAvailableUsesHTTPS (150ms)
 ✗ #testInstallBaselineWhileMissingRepositoryIsInstalledIsPossible (156ms)
 ✗ #testInstallBaselineWithConflictingRepositoryInDiskThrowsError (146ms)
 ✗ #testInstallingAMetacelloBaselineCreatesAnIcebergRepository (147ms)
 ✗ #testNewRepositoryPackagesAreClean (142ms)
 ✗ #testProjectDirtiness (164ms)
 ✗ #testProjectFileFormat (144ms)
 ✗ #testProjectHasDescriptor (142ms)
 ✗ #testInstallBaselineWhenNoSSHIsAvailableUsesHTTPS (166ms)
 ✗ #testInstallBaselineWhileMissingRepositoryIsInstalledIsPossible (463ms)
 ✗ #testInstallBaselineWithConflictingRepositoryInDiskThrowsError (455ms)
 ✗ #testInstallingAMetacelloBaselineCreatesAnIcebergRepository (462ms)
 ✗ #testNewRepositoryPackagesAreClean (448ms)
 ✗ #testProjectDirtiness (460ms)
 ✗ #testProjectFileFormat (457ms)
 ✗ #testProjectHasDescriptor (467ms)
 ✗ #testInstallBaselineWhenNoSSHIsAvailableUsesHTTPS (435ms)
 ✗ #testInstallBaselineWhileMissingRepositoryIsInstalledIsPossible (461ms)
 ✗ #testInstallBaselineWithConflictingRepositoryInDiskThrowsError (499ms)
 ✗ #testInstallingAMetacelloBaselineCreatesAnIcebergRepository (459ms)
 ✗ #testNewRepositoryPackagesAreClean (555ms)
 ✗ #testProjectDirtiness (445ms)
 ✗ #testProjectFileFormat (454ms)
 ✗ #testProjectHasDescriptor (477ms)
 ✗ #testInstallBaselineWhenNoSSHIsAvailableUsesHTTPS (437ms)
 ✗ #testInstallBaselineWhileMissingRepositoryIsInstalledIsPossible (448ms)
 ✗ #testInstallBaselineWithConflictingRepositoryInDiskThrowsError (470ms)
 ✗ #testInstallingAMetacelloBaselineCreatesAnIcebergRepository (434ms)
 ✗ #testNewRepositoryPackagesAreClean (449ms)
 ✗ #testProjectDirtiness (449ms)
 ✗ #testProjectFileFormat (436ms)
 ✗ #testProjectHasDescriptor (446ms)
 ✗ #testInstallBaselineWhenNoSSHIsAvailableUsesHTTPS (445ms)
 ✗ #testInstallBaselineWhileMissingRepositoryIsInstalledIsPossible (600ms)
 ✗ #testInstallBaselineWithConflictingRepositoryInDiskThrowsError (437ms)
 ✗ #testInstallingAMetacelloBaselineCreatesAnIcebergRepository (565ms)
 ✗ #testNewRepositoryPackagesAreClean (437ms)
 ✗ #testProjectDirtiness (434ms)
 ✗ #testProjectFileFormat (464ms)
 ✗ #testProjectHasDescriptor (458ms)

IceSinglePackageLocalGitRepositoryWithDotSubdirectoryTest
 ✗ #testAddNewRemoteListsRemote (229ms)
 ✗ #testNewRepositoryHasNoRemotes (223ms)

IceMultiplePackageLocalGitRepositoryTest
 ✗ #testAddNewRemoteListsRemote (229ms)
 ✗ #testNewRepositoryHasNoRemotes (222ms)


  Executed 2068 Tests with 1 Failures and 515 Errors in 315.04s.

```

**Comment by estebanlm** [comment]
yeah, because I need to first process a PR in libgit2-bindings :P

**Review by jecisc — APPROVED** [review]
Maybe we should use the theme for the colors but this already improve a lot the situation :)

**Comment by estebanlm** [comment]
I check it looks good in both, that's good enough for now :P

**Comment by jecisc** [comment]
The change seems ok, should we merge?

**Pull request merged**
