### PR TITLE
1257-Cannot-change-class-that-have-an-inst-var-of-the-same-name-as-a-class-inst-var-

### LINKED ISSUE #1257: Cannot change class that have an inst var of the same name as a class inst var
The problem arises if you try to rename a class that has a class inst var of the same name as an inst var.

While trying to commit, you will pass by the method MCClassDefinition>>#initializeWithName:superclassName:traitComposition:classTraitComposition:category:instVarNames:classVarNames:poolDictionaryNames:classInstVarNames:type:comment:commentStamp: but instead of getting an array of inst var names, you will get a string.

### PR DESCRIPTION
**Pull request by jecisc**
Do not give strings but array to MCClassDefinition.

Fixes #1257

### CODE REVIEW

**Review by myroslavarm — APPROVED** [review]
looks good!

**Comment by estebanlm** [comment]
not sure why tests fail :P

**Comment by jecisc** [comment]
IIRC, tests were already failing before Instarted to do my PRs on Iceberg.

**Comment by guillep** [comment]
There is a problem with Comander baseline loading

```
Project: Commander baselineSubscriptOutOfBounds: 2
746ByteString(Object)>>errorSubscriptBounds:
747ByteString(Object)>>at:
748ByteString>>at:
749ByteString(SequenceableCollection)>>second
750MetacelloPharoPlatform(MetacelloPlatform)>>extractTypeFromDescription:
751MetacelloPharoPlatform(MetacelloPharoCommonPlatform)>>extractTypeFromDescription:
752MetacelloRepositorySpec>>extractTypeFromDescription
753MetacelloRepositorySpec>>type
754[ :each | each isAvailableFor: aRepositorySpec type ] in MCRepository class>>newRepositoryFromSpec:on: in Block: [ :each | each isAvailableFor: aRepositorySpec typ...etc...
755[ :each | 
756(aBlock value: each)
757	ifTrue: [ ^ foundBlock cull: each ] ] in OrderedCollection(Collection)>>detect:ifFound:ifNone: in Block: [ :each | ...
758OrderedCollection>>do:
759OrderedCollection(Collection)>>detect:ifFound:ifNone:
760OrderedCollection(Collection)>>detect:ifNone:
761MCRepository class>>newRepositoryFromSpec:on:
762MetacelloPharoPlatform(MetacelloPlatform)>>createRepository:
763MetacelloMCBaselineProject(MetacelloMCProject)>>createRepository:
764MetacelloRepositorySpec>>createRepository
765[ aSpec createRepository ] in [ :aSpec | 
766| description repo |
767description := aSpec description.
768(repo := repositories
769	detect: [ :rep | rep description = description ]
770	ifNone: [ aSpec createRepository ]) ~~ nil
771	ifTrue: [ repos add: repo ] ] in MetacelloEnsureFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>repositoriesFrom:ignoreOverrides: in Block: [ aSpec createRepository ]
772Array(Collection)>>detect:ifFound:ifNone:
773Array(Collection)>>detect:ifNone:
774[ :aSpec | 
775| description repo |
776description := aSpec description.
777(repo := repositories
778	detect: [ :rep | rep description = description ]
779	ifNone: [ aSpec createRepository ]) ~~ nil
780	ifTrue: [ repos add: repo ] ] in MetacelloEnsureFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>repositoriesFrom:ignoreOverrides: in Block: [ :aSpec | ...
781Array(SequenceableCollection)>>do:
782MetacelloEnsureFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>repositoriesFrom:ignoreOverrides:
783MetacelloEnsureFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>repositoriesFrom:
784MetacelloPackageSpec>>explicitLoadUsing:
785MetacelloPackageSpec>>ensureLoadUsing:
786MetacelloMCBaselineOfProjectSpec(MetacelloMCProjectSpec)>>ensureLoadUsing:
787[ super ensureLoadUsing: aLoader ] in MetacelloMCBaselineOfProjectSpec>>ensureLoadUsing: in Block: [ super ensureLoadUsing: aLoader ]
788BlockClosure>>on:do:
789MetacelloMCBaselineOfProjectSpec>>ensureLoadUsing:
```

**Comment by jecisc** [comment]
@MarcusDenker No it cannot because the version integrated in Pharo 8 is a previous version in order to be able to revert changes to Spec. 

The dev branch of Iceberg still have this problem.

**Comment by guillep** [comment]
This issue is fixed in 1.8 which is the current master branch.
The spec2 migration branch (1.9) is being merged with this too.

**Pull request closed without merging**
