### PR TITLE
Update users of IceTipStandardAction to use #newXAction + #executeWithContext: pattern (fixes #1779)

### LINKED ISSUE #1779: Reload raised an error because context is nil
```
IceTipStandardAction >> basicExecute

	| result |
	 context application
		informUser: self message
		during: [ result := actionBlock cull: self context ].
	successAnnounceBlock 
		ifNotNil: [ Iceberg announcer announce: successAnnounceBlock value ].
	^ result
```

The problem is that it is unclear how to reach the current application.

### PR DESCRIPTION
**Pull request by daniels220**
Fixes nil DNU #application errors for package reload/remove/unload, tag delete, and method version load (fixes #1779).

* Also remove extraneous IceRepositoryModified when the action already has #onSuccessRepositoryModified.
* Add missing ^return in IceTipVersionHistoryModel>>retrieveHistory.
* Remove IceTipStandardAction>>execute: as execution without a context will ~always fail and the pattern is to assign the action first, then the context at time of execution. No references remain in Iceberg packages, and in fact all remaining references are self-sends, so clearly aren't sent to IceTipStandardAction.
* Consistent classification for #execute methods in IceTipCommand hierarchy

### CODE REVIEW

**Comment by Ducasse** [comment]
Thanks for the PR.

**Comment by guillep** [comment]
Thanks!

**Comment by guillep** [comment]
Oh there are conflicts, I'll push them to the end of the queue

**Comment by guillep** [comment]
Hi @daniels220 I resolved the conflict locally but it seems you did not give rights to push to your branch so I cannot fix it :)

**Comment by daniels220** [comment]
Ah, I didn't realize you were going to resolve them, so I went ahead and did so. No _actual_ conflicts—doing a back-merge in Iceberg didn't flag anything—just Git not being very syntax-aware.

**Comment by guillep** [comment]
> Ah, I didn't realize you were going to resolve them, so I went ahead and did so. No _actual_ conflicts—doing a back-merge in Iceberg didn't flag anything—just Git not being very syntax-aware.

Sure no problem!

Thanks again!

**Pull request merged**
