### PR TITLE
feat: update Fuel to 5.0.6

### LINKED ISSUE #11322: Fuel update causes DNU in iceberg
**Bug description**
Here is an example to reproduce:
```smalltalk
IceCredentialStore current
		storeCredential: (IcePlaintextCredentials new 
			username: 'foo';
			password: 'bar';
			host: 'github.com';
			yourself).
```
After the evaluation of the code snippet, you get:
`Instance of FLMaterializer class did not understand #materializeFromFileNamed:`

**Expected behavior**
No error

**Version information:**
 since Pharo 11 f14f93ce19af5dce174fcabf7fae6a488eaa19d3
related to https://github.com/pharo-project/pharo/pull/11133

@theseion any idea?

### PR DESCRIPTION
**Pull request by theseion**
@MarcusDenker this PR fixes https://github.com/pharo-project/pharo/issues/11322. I had overlooked that Iceberg is a separate repository.

### CODE REVIEW

**Comment by theseion** [comment]
Tests fail because Pharo 10 still comes with the older version of Fuel.

**Comment by demarey** [comment]
> Tests fail because Pharo 10 still comes with the older version of Fuel.

I updated GH action to run also on P11. Could you update your PR after merging the current dev-2 branch in your branch?

**Comment by theseion** [comment]
Done.

**Comment by demarey** [comment]
tests are now green on P11. Thanks

**Comment by astares** [comment]
@demarey / @theseion / @MarcusDenker 

I still have this issue when I download a fresh latest Pharo 11 image from ZeroConf using Ubuntu:

Baseline still shows the "v0.9.9f" insteaf of "v0.9.9g"

image

Image signature is 

Image
-----
/home/kiwi/pharo/pharo11/build/Pharo.image
Pharo11.0.0
Build information: Pharo-11.0.0+build.76.sha.540ecb28a2c790b3ce5a862c735bd3b6a14ce0a0 (64 Bit)
Unnamed


Do we need to update to a newer Iceberg in Pharo 11 now...

**Comment by theseion** [comment]
Maybe a loading issue in Pharo? The code is there on the dev-2.0 branch: https://github.com/pharo-vcs/iceberg/blob/ba4da3970c4db52e78e7d97e4a6ea2c69ddc2ca2/Iceberg/IceCredentialStore.class.st#L112

**Comment by astares** [comment]
@theseion Have no glue on the dependency or inclusion procedure.

Maybe a release of Iceberg needs to be done that is then referenced and loaded in P11

**Comment by demarey** [comment]
@theseion @astares integration is automated but will only happen if there is a new pharo build triggered (e.g. by a PR).
I just triggered a new build manually (job Pharo11/77). When it is finished, the current dev-2.0 branch of Iceberg should be integrated in P11

**Comment by astares** [comment]
@demarey OK - thanks! Will try this evening

**Pull request merged**
