### PR TITLE
Showing Package Icon in the Iceberg UI

### LINKED ISSUE #1441: Use Package Icon also in Iceberg UI
- Calypso System browser has an **icon for packages**
- Iceberg should use the same icon for windows showing packages

image

### PR DESCRIPTION
**Pull request by tesonep**
Fix #1441

### CODE REVIEW

**Comment by tinchodias** [comment]
Looks good!

**Comment by astares** [comment]
Yes

image

**Comment by tinchodias** [comment]
IceTipWorkingCopyBrowserWithRemoteTest tests fail because of this change. I can't push a change because the branch is in your fork, @tesonep

**Comment by tinchodias** [comment]
Only, in 3 test cases, change 1 by 2, for the name of column.

**Pull request merged**
